name: Build images

on:
  - push

jobs:
  collect-versions:
    runs-on: ubuntu-latest
    outputs:
      plone-versions-matrix: ${{ steps.set-matrix.outputs.plone-versions-matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        name: Collect plone versions to build
        run: |
          # list all directories at depth 2 and turn it into a JSON array (as a string)
          JSON=$(find * -maxdepth 1 -mindepth 1  -type d -not -name '.git*' -not -name .| sed -Ez '$ s/\n+$//'  | jq -R -s -c 'split("\n")')
          # Output the string representing a JSON array of all versions present
          echo "::set-output name=plone-versions-matrix::${JSON//'%'/'%25'}"

  build:
    runs-on: ubuntu-latest
    needs: collect-versions
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "36"
          - "37"
          - "38"
          - "39"
        # Get the Plone versions from the previous step
        plone-version: ${{fromJson(needs.collect-versions.outputs.plone-versions-matrix)}}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Check if we should build Plone ${{ matrix.plone-version }} in python ${{ matrix.python-version }}
        id: check_dockerfile
        uses: andstor/file-existence-action@v1
        with:
          files: ./${{ matrix.plone-version }}/Dockerfile.python${{ matrix.python-version }}

      - name: Build ${{ matrix.plone-version }} in python ${{ matrix.python-version }}
        uses: docker/build-push-action@v2
        if: steps.check_dockerfile.outputs.files_exists == 'true'
        with:
          push: false
          tags: user/app:latest
          context: ./${{ matrix.plone-version }}
          file: ./${{ matrix.plone-version }}/Dockerfile.python${{ matrix.python-version }}
